# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Steganography-gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

import steganography

class Ui_Steganography(object):
    image_1 = ""
    image_2 = ""
    image_3 = ""

    def selectimage_1(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getOpenFileName(None, "QFileDialog.getOpenFileName()", "",
                                                  "Image Files (*.jpg)", options=options)
        if fileName:
            self.image_1 = fileName
            self.lable_img_1.setPixmap(QtGui.QPixmap(self.image_1))

    def selectimage_2(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getOpenFileName(None, "QFileDialog.getOpenFileName()", "",
                                                  "Image Files (*.jpg)", options=options)
        if fileName:
            self.image_2 = fileName
            self.lable_img_2.setPixmap(QtGui.QPixmap(self.image_2))

    def selectimage_3(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getOpenFileName(None, "QFileDialog.getOpenFileName()", "",
                                                  "Image Files (*.png)", options=options)
        if fileName:
            self.image_3 = fileName
            self.lable_img_3.setPixmap(QtGui.QPixmap(self.image_3))

    def encryptClicked(self):
        filename = self.text_filename.text()
        steganography.merge(self.image_1, self.image_2, filename + ".png")

    def decryptClicked(self):
        filename = self.text_filename_2.text()
        steganography.unmerge(self.image_3,filename)

    def setupUi(self, Steganography):
        Steganography.setObjectName("Steganography")
        Steganography.resize(613, 527)
        Steganography.setStyleSheet("bacground-color:rgb(0, 255, 127)")
        Steganography.setAnimated(False)
        Steganography.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Steganography)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setEnabled(True)
        self.tab_widget.setGeometry(QtCore.QRect(0, 0, 611, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setAutoFillBackground(False)
        self.tab_widget.setObjectName("tab_widget")
        self.encrypt = QtWidgets.QWidget()
        self.encrypt.setStyleSheet("")
        self.encrypt.setObjectName("encrypt")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.encrypt)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 251, 281))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.select_button_1 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.select_button_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_button_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_button_1.setAutoDefault(False)
        self.select_button_1.setObjectName("select_button_1")
        self.select_button_1.clicked.connect(self.selectimage_1)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.select_button_1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.select_button_2 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.select_button_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_button_2.setObjectName("select_button_2")
        self.select_button_2.clicked.connect(self.selectimage_2)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.select_button_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.text_filename = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.text_filename.setObjectName("text_filename")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.text_filename)
        self.line = QtWidgets.QFrame(self.encrypt)
        self.line.setGeometry(QtCore.QRect(0, 450, 601, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.encrypt)
        self.line_2.setGeometry(QtCore.QRect(350, -10, 16, 471))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.encryptButton = QtWidgets.QPushButton(self.encrypt)
        self.encryptButton.setGeometry(QtCore.QRect(500, 470, 75, 23))
        self.encryptButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.encryptButton.setObjectName("encryptButton")
        self.encryptButton.clicked.connect(self.encryptClicked)
        self.label_9 = QtWidgets.QLabel(self.encrypt)
        self.label_9.setGeometry(QtCore.QRect(370, 10, 47, 13))
        self.label_9.setObjectName("label_9")
        self.lable_img_1 = QtWidgets.QLabel(self.encrypt)
        self.lable_img_1.setGeometry(QtCore.QRect(400, 70, 151, 131))
        self.lable_img_1.setScaledContents(True)
        self.lable_img_1.setObjectName("lable_img_1")
        self.lable_img_2 = QtWidgets.QLabel(self.encrypt)
        self.lable_img_2.setGeometry(QtCore.QRect(400, 270, 151, 131))
        self.lable_img_2.setScaledContents(True)
        self.lable_img_2.setObjectName("lable_img_2")
        self.tab_widget.addTab(self.encrypt, "")
        self.decryp = QtWidgets.QWidget()
        self.decryp.setObjectName("decryp")
        self.formLayoutWidget = QtWidgets.QWidget(self.decryp)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 231))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.select_button_3 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.select_button_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_button_3.setObjectName("select_button_3")
        self.select_button_3.clicked.connect(self.selectimage_3)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.select_button_3)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.text_filename_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.text_filename_2.setObjectName("text_filename_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_filename_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.line_3 = QtWidgets.QFrame(self.decryp)
        self.line_3.setGeometry(QtCore.QRect(0, 450, 611, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.decryp)
        self.line_4.setGeometry(QtCore.QRect(350, 0, 16, 461))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_12 = QtWidgets.QLabel(self.decryp)
        self.label_12.setGeometry(QtCore.QRect(370, 10, 47, 13))
        self.label_12.setObjectName("label_12")
        self.decryptButton = QtWidgets.QPushButton(self.decryp)
        self.decryptButton.setGeometry(QtCore.QRect(500, 460, 75, 23))
        self.decryptButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.decryptButton.setObjectName("decryptButton")
        self.decryptButton.clicked.connect(self.decryptClicked)
        self.lable_img_3 = QtWidgets.QLabel(self.decryp)
        self.lable_img_3.setGeometry(QtCore.QRect(410, 50, 151, 131))
        self.lable_img_3.setScaledContents(True)
        self.lable_img_3.setObjectName("lable_img_3")
        self.tab_widget.addTab(self.decryp, "")
        Steganography.setCentralWidget(self.centralwidget)
        self.retranslateUi(Steganography)
        self.tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Steganography)

    def retranslateUi(self, Steganography):
        _translate = QtCore.QCoreApplication.translate
        Steganography.setWindowTitle(_translate("Steganography", "Steganography"))
        self.label_5.setText(_translate("Steganography", "Select Image 1:"))
        self.select_button_1.setText(_translate("Steganography", "Select"))
        self.label_6.setText(_translate("Steganography", "Select Image 2:"))
        self.select_button_2.setText(_translate("Steganography", "Select"))
        self.label_2.setText(_translate("Steganography", "Output File:"))
        self.label_7.setText(_translate("Steganography", "Filename"))
        self.encryptButton.setText(_translate("Steganography", "Encrypt"))
        self.label_9.setText(_translate("Steganography", "Preview:"))
        self.lable_img_1.setText(_translate("Steganography", "Image 1"))
        self.lable_img_2.setText(_translate("Steganography", "Image 2"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.encrypt), _translate("Steganography", "Encrypt"))
        self.label.setText(_translate("Steganography", "Select Image:"))
        self.select_button_3.setText(_translate("Steganography", "Select"))
        self.label_3.setText(_translate("Steganography", "Output File:"))
        self.label_8.setText(_translate("Steganography", "Filename"))
        self.label_12.setText(_translate("Steganography", "Preview:"))
        self.decryptButton.setText(_translate("Steganography", "Decrypt"))
        self.lable_img_3.setText(_translate("Steganography", "Image "))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.decryp), _translate("Steganography", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Steganography = QtWidgets.QMainWindow()
    ui = Ui_Steganography()
    ui.setupUi(Steganography)
    Steganography.show()
    sys.exit(app.exec_())
